export const SETSIMPSONSDATA = "SETSIMPSONSDATA";
export const SORTDATA = "SORTDATA";
export const SEARCHDATA = "SEARCHDATA";
export const TOGGLEQUOTE = "TOGGLEQUOTE";
export const DELETEQUOTE = "DELETEQUOTE";
export const EDITQUOTE = "EDITQUOTE";
